image: python:3.9

stages:
  - codestyle

before_script:
  - python --version ; pip --version
  - pip install poetry
  - poetry config virtualenvs.in-project true
  - echo "Installing packages..."
  - poetry install --only testing

flake8:
  stage: codestyle
  script:
    - echo "Starting flake8"
    - poetry run flake8

black:
  stage: codestyle
  script:
    - echo "Starting black"
    - poetry run black --check .
